### ISSUE TITLE
Empty notification shouldn't be visible

### ISSUE THREAD

**Issue by nitehu** [ogarcia/ultrasonic#621] opened 2021-11-01 19:43 UTC
## Problem description

Sometimes Ultrasonic displays a stuck empty notification.
This shouldn't happen, when the notification would be empty, the service should be stopped and the notification should be removed.

This problem isn't trivial to reproduce, it may be concurrency related.

**Comment by tzugen** [comment] 2021-11-09 16:35
Yes I saw it also once since updating to android 30.
I could't reproduce it also.

**Comment by tzugen** [comment] 2021-11-20 16:12
I can now reliably reproduce it:
- Play some music in Ultrasonic and pause it
- Leave the app
- Restart the device.

.> You will get the empyt notification

**Comment by tzugen** [comment] 2021-11-20 16:13
When I remove the AutoMediaBrowserService from the Manifest it seems to stop happening,

**Comment by tzugen** [comment] 2021-11-20 16:17
````
2021-11-20 17:13:44.656 3331-3331/com.android.bluetooth I/AvrcpBrowsedPlayerWrapper: Wrapping Media Browser org.moire.ultrasonic.debug
2021-11-20 17:13:45.077 2841-2931/system_process I/ActivityManager: Start proc 4825:org.moire.ultrasonic.debug/u0a198 for service {org.moire.ultrasonic.debug/org.moire.ultrasonic.service.AutoMediaBrowserService}
2021-11-20 17:13:45.087 4825-4825/org.moire.ultrasonic.debug I/ltrasonic.debu: Late-enabling -Xcheck:jni
2021-11-20 17:13:45.125 4825-4825/org.moire.ultrasonic.debug I/ltrasonic.debu: Unquickening 14 vdex files!
2021-11-20 17:13:45.635 4825-4825/org.moire.ultrasonic.debug D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2021-11-20 17:13:47.323 4825-4839/org.moire.ultrasonic.debug I/ltrasonic.debu: Background young concurrent copying GC freed 6887(491KB) AllocSpace objects, 0(0B) LOS objects, 93% free, 1713KB/25MB, paused 65us total 190.895ms
2021-11-20 17:13:50.149 4825-4825/org.moire.ultrasonic.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-11-20 17:13:50.150 4825-4825/org.moire.ultrasonic.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-11-20 17:13:50.242 4825-4825/org.moire.ultrasonic.debug W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
2021-11-20 17:13:50.242 4825-4825/org.moire.ultrasonic.debug W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.app.UApp.$jacocoInit(Unknown Source:13)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.app.UApp.<clinit>(Unknown Source:0)
2021-11-20 17:13:50.243 4825-4825/org.moire.ultrasonic.debug W/System.err:     at java.lang.Class.newInstance(Native Method)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:237)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.os.Looper.loop(Looper.java:223)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7664)
2021-11-20 17:13:50.244 4825-4825/org.moire.ultrasonic.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-20 17:13:50.245 4825-4825/org.moire.ultrasonic.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-11-20 17:13:50.245 4825-4825/org.moire.ultrasonic.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-11-20 17:13:50.252 4825-4825/org.moire.ultrasonic.debug W/System.err: Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
2021-11-20 17:13:50.252 4825-4825/org.moire.ultrasonic.debug W/System.err:     at libcore.io.Linux.open(Native Method)
2021-11-20 17:13:50.252 4825-4825/org.moire.ultrasonic.debug W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2021-11-20 17:13:50.252 4825-4825/org.moire.ultrasonic.debug W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
2021-11-20 17:13:50.252 4825-4825/org.moire.ultrasonic.debug W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2021-11-20 17:13:50.253 4825-4825/org.moire.ultrasonic.debug W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7550)
2021-11-20 17:13:50.253 4825-4825/org.moire.ultrasonic.debug W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:478)
2021-11-20 17:13:50.253 4825-4825/org.moire.ultrasonic.debug W/System.err: 	... 23 more
2021-11-20 17:13:50.310 4825-4825/org.moire.ultrasonic.debug I/MultiDex: VM with version 2.1.0 has multidex support
2021-11-20 17:13:50.310 4825-4825/org.moire.ultrasonic.debug I/MultiDex: Installing application
2021-11-20 17:13:50.310 4825-4825/org.moire.ultrasonic.debug I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2021-11-20 17:13:50.861 4825-4825/org.moire.ultrasonic.debug I/TimberKoinLogger: [init] declare Android Context
2021-11-20 17:13:51.291 4825-4825/org.moire.ultrasonic.debug I/TimberKoinLogger: loaded 31 definitions - 52.893078 ms
2021-11-20 17:13:51.801 4825-4825/org.moire.ultrasonic.debug W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
2021-11-20 17:13:52.546 4825-4825/org.moire.ultrasonic.debug D/ActiveServerProvider$getActiveServer: getActiveServer retrieved from DataBase, id: 2 cachedServer: ServerSetting(id=2, index=2, name=mmuk, url=https://muk.undo.it, color=null, userName=admin, password=merge-bien-bulbul, jukeboxByDefault=false, allowSelfSignedCertificate=false, ldapSupport=false, musicFolderId=null, minimumApiVersion=1.15.0, chatSupport=null, bookmarkSupport=null, shareSupport=null, podcastSupport=null)
2021-11-20 17:13:52.650 4825-4825/org.moire.ultrasonic.debug W/ltrasonic.debu: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
2021-11-20 17:13:52.650 4825-4825/org.moire.ultrasonic.debug W/ltrasonic.debu: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
2021-11-20 17:13:52.650 4825-4825/org.moire.ultrasonic.debug W/ltrasonic.debu: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
2021-11-20 17:13:52.700 4825-4825/org.moire.ultrasonic.debug I/ActiveServerProvider: Switching to new database, id:2
2021-11-20 17:13:53.001 4825-4825/org.moire.ultrasonic.debug D/MediaSessionHandler: MediaSessionHandler.initialize Creating Media Session
2021-11-20 17:13:53.080 4825-4825/org.moire.ultrasonic.debug I/MediaSessionHandler: MediaSessionHandler.initialize Media Session created
2021-11-20 17:13:53.080 4825-4825/org.moire.ultrasonic.debug I/AutoMediaBrowserService: AutoMediaBrowserService onCreate finished
2021-11-20 17:13:53.084 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.moire.ultrasonic.debug
2021-11-20 17:13:53.086 3331-3331/com.android.bluetooth I/AvrcpMediaPlayerList: Adding wrapped media player: org.moire.ultrasonic.debug at key: 5
2021-11-20 17:13:53.101 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.moire.ultrasonic.debug
2021-11-20 17:13:53.101 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: Already have a controller for the player: org.moire.ultrasonic.debug, updating instead
2021-11-20 17:13:53.115 4825-4825/org.moire.ultrasonic.debug D/AutoMediaBrowserService: AutoMediaBrowserService onGetRoot called. clientPackageName: com.android.bluetooth; clientUid: 1002
2021-11-20 17:13:53.117 3331-3331/com.android.bluetooth I/AvrcpBrowsedPlayerWrapper: onConnected: org.moire.ultrasonic.debug is connected
2021-11-20 17:13:53.117 3331-3331/com.android.bluetooth D/AvrcpBrowsablePlayerConnector: Browse player callback called: package=org.moire.ultrasonic.debug : status=0
2021-11-20 17:13:53.117 3331-3331/com.android.bluetooth I/AvrcpBrowsablePlayerConnector: Checking root contents for org.moire.ultrasonic.debug
2021-11-20 17:13:53.139 4825-4825/org.moire.ultrasonic.debug I/MediaSessionHandler: MediaSessionHandler.release Media Session released
2021-11-20 17:13:53.143 4825-4825/org.moire.ultrasonic.debug I/AutoMediaBrowserService: AutoMediaBrowserService onDestroy finished
2021-11-20 17:13:53.180 4825-4825/org.moire.ultrasonic.debug D/MediaSessionHandler: MediaSessionHandler.initialize Creating Media Session
2021-11-20 17:13:53.249 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.moire.ultrasonic.debug
2021-11-20 17:13:53.249 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: Already have a controller for the player: org.moire.ultrasonic.debug, updating instead
2021-11-20 17:13:53.249 4825-4825/org.moire.ultrasonic.debug I/MediaSessionHandler: MediaSessionHandler.initialize Media Session created
2021-11-20 17:13:53.250 4825-4825/org.moire.ultrasonic.debug I/AutoMediaBrowserService: AutoMediaBrowserService onCreate finished
2021-11-20 17:13:53.264 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.moire.ultrasonic.debug
2021-11-20 17:13:53.264 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: Already have a controller for the player: org.moire.ultrasonic.debug, updating instead
2021-11-20 17:13:53.272 4825-4825/org.moire.ultrasonic.debug D/AutoMediaBrowserService: AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService...
2021-11-20 17:13:53.540 4825-4825/org.moire.ultrasonic.debug I/MediaPlayerController: MediaPlayerController constructed
2021-11-20 17:13:53.550 4825-4825/org.moire.ultrasonic.debug D/JukeboxMediaPlayer: Jukebox Service setting enabled to false
2021-11-20 17:13:53.614 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.moire.ultrasonic.debug
2021-11-20 17:13:53.614 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: Already have a controller for the player: org.moire.ultrasonic.debug, updating instead
2021-11-20 17:13:54.566 4825-4825/org.moire.ultrasonic.debug D/JukeboxMediaPlayer: Stopped Jukebox Service
2021-11-20 17:13:54.567 4825-4825/org.moire.ultrasonic.debug I/MediaPlayerController: MediaPlayerController created
2021-11-20 17:13:54.583 4825-4825/org.moire.ultrasonic.debug I/MediaPlayerLifecycleSupport: LifecycleSupport created
2021-11-20 17:13:54.658 3331-3331/com.android.bluetooth D/AvrcpBrowsablePlayerConnector: Disconnecting org.moire.ultrasonic.debug
2021-11-20 17:13:54.667 3331-3331/com.android.bluetooth D/AvrcpMediaPlayerList: Already have a controller for the player: org.moire.ultrasonic.debug, updating instead
2021-11-20 17:13:54.714 4825-6052/org.moire.ultrasonic.debug I/FileUtil: Deserialized object from /data/user/0/org.moire.ultrasonic.debug/cache/downloadstate.ser
2021-11-20 17:13:54.715 4825-6052/org.moire.ultrasonic.debug I/PlaybackStateSerializer: Deserialized currentPlayingIndex: 0, currentPlayingPosition: 3175 
2021-11-20 17:13:54.757 4825-6052/org.moire.ultrasonic.debug I/TetheringManager: registerTetheringEventCallback:org.moire.ultrasonic.debug
2021-11-20 17:13:54.806 4825-6052/org.moire.ultrasonic.debug I/Downloader: Downloader started
2021-11-20 17:13:54.813 4825-6845/org.moire.ultrasonic.debug W/Downloader: Checking Downloads
2021-11-20 17:13:54.840 4825-6845/org.moire.ultrasonic.debug I/Downloader: Downloader stopped
2021-11-20 17:13:54.843 4825-6845/org.moire.ultrasonic.debug W/Downloader: Checking Downloads
2021-11-20 17:13:54.865 4825-6845/org.moire.ultrasonic.debug I/Downloader: Downloader stopped
2021-11-20 17:13:55.211 4825-6050/org.moire.ultrasonic.debug I/CacheCleaner$Companion: File system       : 6,33 GB of 52,54 GB available
2021-11-20 17:13:55.213 4825-6050/org.moire.ultrasonic.debug I/CacheCleaner$Companion: Cache limit       : 8,79 GB
2021-11-20 17:13:55.213 4825-6050/org.moire.ultrasonic.debug I/CacheCleaner$Companion: Cache size before : 4,13 GB
2021-11-20 17:13:55.214 4825-6050/org.moire.ultrasonic.debug I/CacheCleaner$Companion: Minimum to delete : 0 B
2021-11-20 17:13:55.217 4825-6050/org.moire.ultrasonic.debug I/CacheCleaner$Companion: Deleted: 0 B
2021-11-20 17:13:56.701 4825-4825/org.moire.ultrasonic.debug D/AutoMediaBrowserService: AutoMediaBrowserService onGetRoot called. clientPackageName: com.android.bluetooth; clientUid: 1002
2021-11-20 17:13:56.702 4825-4825/org.moire.ultrasonic.debug D/AutoMediaBrowserService: AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService...
2021-11-20 17:13:56.996 4825-6853/org.moire.ultrasonic.debug E/MediaPlayerService$Companion$executeOnStartedMediaPlayerService$t: ExecuteOnStarted.. failed to get a MediaPlayerService instance!
2021-11-20 17:13:58.868 4825-4825/org.moire.ultrasonic.debug I/ShufflePlayBuffer: ShufflePlayBuffer created
2021-11-20 17:13:58.870 4825-4825/org.moire.ultrasonic.debug I/LocalMediaPlayer: LocalMediaPlayer created
2021-11-20 17:13:58.942 2841-5040/system_process W/ActivityManager: Foreground service started from background can not have location/camera/microphone access: service org.moire.ultrasonic.debug/org.moire.ultrasonic.service.MediaPlayerService
2021-11-20 17:13:58.954 4825-7920/org.moire.ultrasonic.debug I/FileUtil: Deserialized object from /data/user/0/org.moire.ultrasonic.debug/cache/equalizer.dat
2021-11-20 17:13:58.956 4825-4825/org.moire.ultrasonic.debug V/MediaPlayerService: Created Foreground notification
2021-11-20 17:13:58.957 4825-4825/org.moire.ultrasonic.debug I/MediaPlayerService: MediaPlayerService created
2021-11-20 17:13:58.959 4825-4825/org.moire.ultrasonic.debug I/AutoMediaBrowserService: AutoMediaBrowserService onDestroy finished
2021-11-20 17:13:58.985 4825-7920/org.moire.ultrasonic.debug E/AudioEffect: set(): AudioFlinger could not create effect e46b26a0-dddd-11db-8afd-0002a5d5c51b / NULL, status: -1
2021-11-20 17:13:58.985 4825-7920/org.moire.ultrasonic.debug E/visualizers-JNI: Visualizer initCheck failed -3
2021-11-20 17:13:58.986 4825-7920/org.moire.ultrasonic.debug E/Visualizer-JAVA: Error code -3 when initializing Visualizer.
2021-11-20 17:13:58.987 4825-7920/org.moire.ultrasonic.debug W/VisualizerController: Failed to create visualizer.
    java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
        at android.media.audiofx.Visualizer.<init>(Visualizer.java:229)
        at org.moire.ultrasonic.audiofx.VisualizerController.create(VisualizerController.java:65)
        at org.moire.ultrasonic.service.LocalMediaPlayer.init$lambda-2(LocalMediaPlayer.kt:117)
        at org.moire.ultrasonic.service.LocalMediaPlayer.lambda$hOjpDlHPKlHT3kENbIJXm_cYtcs(Unknown Source:0)
        at org.moire.ultrasonic.service.-$$Lambda$LocalMediaPlayer$hOjpDlHPKlHT3kENbIJXm_cYtcs.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
2021-11-20 17:13:59.151 2841-2841/system_process D/NotificationService: 0|org.moire.ultrasonic.debug|3033|null|10198: granting content://settings/system/notification_sound
2021-11-20 17:13:59.153 2841-2841/system_process D/NotificationService: 0|org.moire.ultrasonic.debug|3033|null|10198: granting content://settings/system/notification_sound
2021-11-20 17:14:31.503 2841-8902/system_process I/PackageDexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/~~y8LqR9bUlPkWR1Nhu-eldw==/org.moire.ultrasonic.debug-iPB3RWt9bplkNsfD29JR7g==/base.apk pkg=org.moire.ultrasonic.debug isa=arm64 dexoptFlags=boot_complete,debuggable,public,enable_hidden_api_checks targetFilter=verify oatDir=/data/app/~~y8LqR9bUlPkWR1Nhu-eldw==/org.moire.ultrasonic.debug-iPB3RWt9bplkNsfD29JR7g==/oat classLoaderContext=PCL[]{PCL[/system/framework/android.test.base.jar]}
2021-11-20 17:14:31.515 2437-3280/? V/installd: DexInv: --- BEGIN '/data/app/~~y8LqR9bUlPkWR1Nhu-eldw==/org.moire.ultrasonic.debug-iPB3RWt9bplkNsfD29JR7g==/base.apk' ---
2021-11-20 17:14:31.555 8932-8932/? I/dex2oat32: /apex/com.android.art/bin/dex2oat32 --input-vdex-fd=-1 --output-vdex-fd=10 --updatable-bcp-packages-file=/system/etc/updatable-bcp-packages.txt --resolve-startup-const-strings=true --max-image-block-size=524288 --compiler-filter=verify --debuggable --classpath-dir=/data/app/~~y8LqR9bUlPkWR1Nhu-eldw==/org.moire.ultrasonic.debug-iPB3RWt9bplkNsfD29JR7g== --class-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]} --generate-mini-debug-info --compact-dex-level=none --compilation-reason=boot
2021-11-20 17:14:36.040 2437-3280/? V/installd: DexInv: --- END '/data/app/~~y8LqR9bUlPkWR1Nhu-eldw==/org.moire.ultrasonic.debug-iPB3RWt9bplkNsfD29JR7g==/base.apk' (success) ---
2021-11-20 17:14:36.399 2841-8902/system_process I/BackgroundDexOptService: Pinning optimized code {org.moire.ultrasonic.debug}
````

The android system starts the MediaBrowserService, the service starts a bunch of app code, and quickly quits again, because there is nothing to do...

**Comment by tzugen** [comment] 2021-12-20 17:47
Related to #426

**Comment by tzugen** [comment] 2022-04-04 06:41
Fixed by  #726

**Comment by ogarcia** [comment] 2022-06-17 06:45
We can confirm that this issue is fixed and close this?

**Comment by tzugen** [comment] 2022-06-19 05:18
Would be very suprised if not.
Please reopen if you see this again (on the beta branch)!

**Closed as completed by tzugen** 2022-06-19 05:18 UTC
Labels: bug
