### ISSUE TITLE
Shuffle setting does not persist after reboot/resume

### ISSUE THREAD

**Issue by fexofenadine** [ogarcia/ultrasonic#767] opened 2022-06-23 06:16 UTC
## Problem description

The beta (4.x) seems to "forget" that shuffle mode is enabled on a currently playing playlist under certain circumstances, such as after a reboot. Can easily be toggled back on but it seems to be a new issue since 3.x

### Steps to reproduce

Select a playlist and toggle shuffle on. Close app and reopen and shuffle is toggled off again.

### Ultrasonic client

 * **Ultrasonic version**: 4.0 beta
 * **Android version**: 13 alpha
 * **Device info**: Pixel 6 Pro

### Server

 * **Server name**: Airsonic Advanced 

Would be nice if there were a configurable setting to restore the old behaviour. Thanks kindly

**Comment by tzugen** [comment] 2022-06-23 06:45
Solution: store the value inside the PlaybackState object and restore it when resuming.

**Comment by tzugen** [comment] 2022-07-05 20:52
Please checkout the PR if the problem is fixed correwctly

**Comment by tzugen** [comment] 2022-07-08 09:46
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/767

**Closed as completed by tzugen** 2022-07-08 09:46 UTC
Labels: feature request, good first issue
