### ISSUE TITLE
Can't play any track

### ISSUE THREAD

**Issue by stemy2** [ogarcia/ultrasonic#694] opened 2022-02-24 07:51 UTC
## Problem description
The app can access to my server, and show my musical library, but says "Warning: no network available" when i'm trying to play a track.

### Steps to reproduce
1. Enable subsonic API and set subsonic password.
2. Add the server
3. Open the server
4. Select a track
5. Try to play it

## System information

 * **Ultrasonic version**: *3.1.1*
 * **Android version**: *Android 8.1*
 * **Device info**: *Samsung Galaxy S7*

## Additional notes

I tried the feature "test the connection", it says that it works.

[ultrasonic.1.log](https://github.com/ultrasonic/ultrasonic/files/8130629/ultrasonic.1.log)

**Comment by nitehu** [comment] 2022-02-25 07:10
Thanks for the report. From the log it seems Ultrasonic can't download the song from the server.
Could you please also provide your server name and version? It is necessary so we can try to reproduce the problem.

**Comment by stemy2** [comment] 2022-02-27 10:23
My server is Funkwhale 1.2.2.

**Comment by Kleinschmidts** [comment] 2022-03-01 13:56
Same here. I am using my own nextcloud server. It seems to be related to internet connection. I am using Blokada5 on android 7.1.1. If I deactivate this everything is working fine, if activated, even with no blocklist at all, i can connect to the server, browse library, only when trying to play a track, says "Warning: no network available".

**Comment by Kleinschmidts** [comment] 2022-03-05 13:38
Meanwhile I would rather blame Blokada5 for this issue. On two other devices (Lineageos 16.0 / Android 9) and a oneplus it works with no issues. Additionally the tablet with Android 7.1.1 has other problems with blokada5, even just downloading some pdf in the browser fails.
Sorry for the noise

**Comment by tzugen** [comment] 2022-03-20 06:53
The only place except VideoPlayer (which is irelevant here) where we emit this warning is in the `NetworkAndStorageChecker`.
The user has reported seeing the problem in API 27. 

I have changed the function `isNetworkConnected` recently, because it had deprecated method calls.

@stemy2 

What network are you seeing this? Wifi or Mobile Data? If Wifi, is your wifi maybe marked as "metered"?
What is your setting in the app regarding requiring wifi for download?

**Comment by tzugen** [comment] 2022-03-20 06:59
What we can do anyway would be to improve the wording of the alert. Fixed in #714

**Closed as completed** 2022-03-21 08:56 UTC
Labels: enhancement
